
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('roles').del()
    .then(function () {
      // Inserts seed entries
      return knex('roles').insert([
        {id: 1, name: 'Software Engineer III', company_id: 3, description: 'As a Software Engineer on our Endpoint team, you will help people worldwide keep their computers and mobile devices safe.  You will help organizations understand and minimize the risks to their environment.  You will face difficult challenges that require creative solutions and a broad array of technical skills.  Your small, Agile engineering team will work with product management, product design, and beta customers to deliver value at a rapid pace'},
        {id: 2, name: 'Full Stack Developer, Node.js / React', company_id: 1, description: 'Help build out a functionally aligned UI architecture with modern JavaScript frameworks and libraries\n Help scale our services & web apps to more than 60k requests per second\n Develop fast, scalable, highly available, and reliable payment engines that will process billions of dollars per year\n Present realtime data to understand customers’ needs before they do\n Dockerize our apps and services for cloud deployment\n Develop features that will drive our business through real-time feedback loops\n Develop a smart service layer that will allow for in-session personalization based off user behavior and data\n Scale our public API to allow other partners to leverage HomeAway services & experiences on third party sites\n Simplify core booking and listing workflow to enhance our travelers & suppliers experience'},
        {id: 3, name: 'Software Engineer', company_id: 6, description: "Assist in translating business requirements into software designs, implementation schedules, and deployment strategies\n Implement software modules, database schemas, deployment and migration scripts\n Define new features insuring a high performing and scalable user experience in the cloud\n Collaborate with peers on technical design, work estimation and feature implementation on data model, business logic, and user interfaces\n Participate in sprint planning by understanding the effort, risk, and priority of remaining work committed to a software release\n Perform peer code reviews and collaborate with team to improve overall code quality\n Contribute ideas for continually improving the team's productivity, release quality, and job enjoyment"},
        {id: 4, name: 'Senior Quality Engineer', company_id: 5, description: 'Work with a product manager to define features, acceptance scenarios, and test cases.\n Write automation tests.\n Advocate for customer experience through consistency and simplicity.\n Work with engineers to ensure test cases are reflected in code and automated tests.\n Identify opportunities to use end to end tests to provide greater value and confidence around software.\n Advocate for practices and tools that promote quality, such as solution design, effective unit testing, static analysis, etc.\n Identify relevant quality metrics for the team like error rates and thresholds.\n Advocate for, implement and monitor tools that provide alerting on those metrics.\n Investigate defects and produce minimum viable test cases to reproduce them.\n Support frequent deployments to production.\n Help foster a culture of pride and obsession around delivering quality software'},
        {id: 5, name: 'Software Engineer, Back-end Java', company_id: 1, description: 'Scale our services to more than 60k requests per second\n Develop fast, scalable, highly available, and reliable payment engines that will process billions of dollars per year\n Use realtime data to understand customers’ needs before they do\n Dockerize our apps and services for cloud deployment\n Develop features that will drive our business through real-time feedback loops\n Develop a smart service layer that will allow for in-session personalization based off user behavior and data\n Scale our public API to allow other partners to leverage HomeAway services & experiences on third party sites\n Simplify core booking and listing workflow to enhance our travelers & suppliers experience'}
      ]);
    });
};
